examples_list = [
    (
        "examples/initial/initial.sv",
        "examples/initial/test_result",
        "examples/initial/aplan",
    ),
    (
        "examples/assigns/assign_1/assign_1.sv",
        "examples/assigns/assign_1/test_result",
        "examples/assigns/assign_1/aplan",
    ),
    (
        "examples/struct/enum/enum.sv",
        "examples/struct/enum/test_result",
        "examples/struct/enum/aplan",
    ),
    (
        "examples/parametrs/parametrs_1/parametrs_1.sv",
        "examples/parametrs/parametrs_1/test_result",
        "examples/parametrs/parametrs_1/aplan",
    ),
    (
        "examples/assert/assert.sv",
        "examples/assert/test_result",
        "examples/assert/aplan",
    ),
    (
        "examples/always/always_@*/always_@*.sv",
        "examples/always/always_@*/test_result",
        "examples/always/always_@*/aplan",
    ),
    (
        "examples/always/always_without_sensetive/always_without_sensetive.sv",
        "examples/always/always_without_sensetive/test_result",
        "examples/always/always_without_sensetive/aplan",
    ),
    (
        "examples/case/case.sv",
        "examples/case/test_result",
        "examples/case/aplan",
    ),
    (
        "examples/if_statemens/if_statement_1/if_statement_1.sv",
        "examples/if_statemens/if_statement_1/test_result",
        "examples/if_statemens/if_statement_1/aplan",
    ),
    (
        "examples/if_statemens/if_statement_2/if_statement_2.sv",
        "examples/if_statemens/if_statement_2/test_result",
        "examples/if_statemens/if_statement_2/aplan",
    ),
    (
        "examples/loops/loop_1/loop_1.sv",
        "examples/loops/loop_1/test_result",
        "examples/loops/loop_1/aplan",
    ),
    (
        "examples/loops/loop_2/loop_2.sv",
        "examples/loops/loop_2/test_result",
        "examples/loops/loop_2/aplan",
    ),
    (
        "examples/loops/while_1/while_1.sv",
        "examples/loops/while_1/test_result",
        "examples/loops/while_1/aplan",
    ),
    (
        "examples/loops/while_2/while_2.sv",
        "examples/loops/while_2/test_result",
        "examples/loops/while_2/aplan",
    ),
    (
        "examples/loops/foreach/foreach.sv",
        "examples/loops/foreach/test_result",
        "examples/loops/foreach/aplan",
    ),
    (
        "examples/loops/forever/forever.sv",
        "examples/loops/forever/test_result",
        "examples/loops/forever/aplan",
    ),
    (
        "examples/task_and_functions/task_1/task_1.sv",
        "examples/task_and_functions/task_1/test_result",
        "examples/task_and_functions/task_1/aplan",
    ),
    (
        "examples/task_and_functions/task_2/task_2.sv",
        "examples/task_and_functions/task_2/test_result",
        "examples/task_and_functions/task_2/aplan",
    ),
    (
        "examples/task_and_functions/function_1/function_1.sv",
        "examples/task_and_functions/function_1/test_result",
        "examples/task_and_functions/function_1/aplan",
    ),
    (
        "examples/task_and_functions/function_2/function_2.sv",
        "examples/task_and_functions/function_2/test_result",
        "examples/task_and_functions/function_2/aplan",
    ),
    (
        "examples/task_and_functions/function_3/function_3.sv",
        "examples/task_and_functions/function_3/test_result",
        "examples/task_and_functions/function_3/aplan",
    ),
    (
        "examples/call/call_1/call_2.sv",
        "examples/call/call_1/test_result",
        "examples/call/call_1/aplan",
    ),
    (
        "examples/sv_example_1/sv_example_1.sv",
        "examples/sv_example_1/test_result",
        "examples/sv_example_1/aplan",
    ),
    (
        "examples/sv_example_2/sv_example_2.sv",
        "examples/sv_example_2/test_result",
        "examples/sv_example_2/aplan",
    ),
]
