name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements_for_testing.txt ]; then pip install -r requirements_for_testing.txt; fi

      - name: Run unit tests
        run: pytest

      - name: Run tests
        run: python scripts/sv2aplan_run_tests.py
